version: "3.1"
services:

  stormy_nginx_subs:
    restart: always
    image: nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - "./d-nginx-subdomains/conf.d:/etc/nginx/conf.d"
      - "/www/pages.charlesreid1.com/htdocs:/www/pages.charlesreid1.com/htdocs:ro"
      - "/www/hooks.charlesreid1.com/htdocs:/www/hooks.charlesreid1.com/htdocs:ro"
      - "/www/bots.charlesreid1.com/htdocs:/www/bots.charlesreid1.com/htdocs:ro"
    ports:
      - "7777:7777"
      - "7778:7778"
      - "7779:7779"

  stormy_captain_hook:
    build: b-captain-hook
    volumes:
      - "/www/pages.charlesreid1.com:/www/pages.charlesreid1.com"
      - "/www/hooks.charlesreid1.com:/www/hooks.charlesreid1.com"
      - "/www/bots.charlesreid1.com:/www/bots.charlesreid1.com"
      - "/tmp/triggers:/tmp/triggers"
      - "./b-captain-hook/hooks:/app/hooks"
    ports:
      - "5000:5000"

