site_name: pod-webhooks
site_url: https://pages.charlesreid1.com/pod-webhooks
repo_name: pod-webhooks
repo_url: https://git.charlesreid1.com/docker/pod-webhooks
edit_uri: ""
copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - "Home": "index.md"
  - "Adding Webhooks": "adding.md"
  - "Running Captain Hook": "running.md"
  - "Captain Hook Startup Services": "services.md"
  - "Captain Hook's Canary": "canary.md"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

strict: true
